// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace popcornLK.Migrations
{
    [DbContext(typeof(Contex))]
    [Migration("20230228145226_sixth")]
    partial class sixth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("popcornLK.Models.Customer", b =>
                {
                    b.Property<string>("NIC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("C_Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("C_Age")
                        .HasColumnType("int");

                    b.Property<string>("C_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NIC");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("popcornLK.Models.Genre", b =>
                {
                    b.Property<int>("Genre_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Genre_Discriptionj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Movies_Count")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Genre_ID");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("popcornLK.Models.Movie", b =>
                {
                    b.Property<int>("M_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("M_Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ratings")
                        .HasColumnType("int");

                    b.Property<string>("RunTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("three_d_or_not")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("M_ID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("popcornLK.Models.Theater", b =>
                {
                    b.Property<int>("T_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comming_Soon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Now_Showing")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("T_Address")
                        .HasColumnType("int");

                    b.Property<string>("T_Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("T_Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("T_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("T_Phone_No")
                        .HasColumnType("int");

                    b.Property<string>("T_Ratings")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("T_Reviews")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("T_ID");

                    b.ToTable("Theaters");
                });

            modelBuilder.Entity("popcornLK.Models.Ticket", b =>
                {
                    b.Property<int>("T_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Seat_No")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ticket_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("T_ID");

                    b.ToTable("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
