// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace popcornLK.Migrations
{
    [DbContext(typeof(Contex))]
    [Migration("20230228100306_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("popcornLK.Models.Customer", b =>
                {
                    b.Property<string>("NIC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("C_Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("C_Age")
                        .HasColumnType("int");

                    b.Property<string>("C_Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NIC");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("popcornLK.Models.Ticket", b =>
                {
                    b.Property<int>("T_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CustomerNIC")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Seat_No")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ticket_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("T_ID");

                    b.HasIndex("CustomerNIC");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("popcornLK.Models.Ticket", b =>
                {
                    b.HasOne("popcornLK.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerNIC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
